src/objects/Camping_Item__c.object
<CustomObject>
    <fields>
        <fullName>Packed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Packed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Camping Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Camping Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camping Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CampingListController.cls
public with sharing class CampingListController {
    @AuraEnabled
    public static List<Camping_Item__c> getItems(){
        List<Camping_Item__c> campingItems = [SELECT Name, Price__c, Quantity__c, Packed__c
                                              FROM Camping_Item__c
                                              LIMIT 10];
        System.debug(LoggingLevel.DEBUG, 'Queried a total of ' + campingItems.size());
        return campingItems;
    }

    @AuraEnabled
    public static Camping_Item__c saveItem(Camping_Item__c campingItem){
        System.debug('Upserting ' + campingItem);
        upsert campingItem;
        return campingItem;
    }
}